### ISSUE TITLE
Experiment with output references

### ISSUE THREAD

**Issue by d01000100** [d01000100/figma-token-engine#25]
StyleDictionary 3.0 introduced the ability to [generate output files with references between tokens](https://amzn.github.io/style-dictionary/#/version_3?id=output-references)

```css
:root {
  --color-red: #ff0000;
  --color-danger: var(--color-red);
  --color-error: var(--color-danger);
}
```

According to StyleDictionary:

> This is useful for outputting themeable and dynamic code.

Experiment with this feature to determine if we can take advantage of it when we multiple themes
